name: main

on:
  push:
    branches:
      - main

jobs:
  sendEmail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @sendgrid/mail

      - name: Create and run email script
        run: |
         echo "const sgMail = require('@sendgrid/mail');" > sendEmail.js
         echo "sgMail.setApiKey(process.env.SENDGRID_API_KEY);" >> sendEmail.js
         echo "" >> sendEmail.js
         echo "const msg = {" >> sendEmail.js
         echo "  to: 'test@example.com'," >> sendEmail.js
         echo "  from: 'test@example.com'," >> sendEmail.js
         echo "  subject: 'Sending with SendGrid is Fun'," >> sendEmail.js
         echo "  text: 'and easy to do anywhere, even with Node.js'," >> sendEmail.js
         echo "  html: '<strong>and easy to do anywhere, even with Node.js</strong>'," >> sendEmail.js
         echo "};" >> sendEmail.js
         echo "" >> sendEmail.js
         echo "sgMail" >> sendEmail.js
         echo "  .send(msg)" >> sendEmail.js
         echo "  .then(() => {" >> sendEmail.js
         echo "    console.log('Email sent');" >> sendEmail.js
         echo "    process.exit(0);" >> sendEmail.js
         echo "  })" >> sendEmail.js
         echo "  .catch((error) => {" >> sendEmail.js
         echo "    console.error('Error sending email:', error);" >> sendEmail.js
         echo "    process.exit(1);" >> sendEmail.js
         echo "  });" >> sendEmail.js

         node sendEmail.js





