name: main

on:
  push:
    branches:
      - main

jobs:
  sendEmail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install nodemailer

      - name: Send email
        run: |
          const nodemailer = require('nodemailer');

          const transporter = nodemailer.createTransport({
            host: 'smtp.sendgrid.net',
            port: 587, // or 465 for SSL connections
            secure: false, // false for unencrypted/TLS connections, true for SSL connections
            auth: {
              user: 'apikey',
              pass: process.env.SENDGRID_API_KEY
            }
          });

          const mailOptions = {
            from: 'argentnos1050@gmail.com',
            to: 'spyfilip@gmail.com',
            subject: 'Sending with SendGrid is Fun',
            text: 'and easy to do anywhere, even with Node.js',
            html: '<strong>and easy to do anywhere, even with Node.js</strong>'
          };

          transporter.sendMail(mailOptions, (error, info) => {
            if (error) {
              console.error('Error sending email:', error);
              process.exit(1);
            } else {
              console.log('Email sent:', info.messageId);
              process.exit(0);
            }
          });




