name: main

on:
  push:
    branches:
      - main

jobs:
  sendEmail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install nodemailer

      - name: Send email
        run: |
         const nodemailer = require('nodemailer');
  
         const transporter = nodemailer.createTransport({
         host: 'smtp.sendgrid.net',
         port: 587,
         secure: false,
         auth: {
          user: 'apikey',
           pass: process.env.SENDGRID_API_KEY
         }
         });
  
         const mailOptions = {
         from: 'sender@example.com',
         to: 'recipient@example.com',
         subject: 'Sending with SendGrid is Fun',
         text: 'and easy to do anywhere, even with Node.js',
         html: '<strong>and easy to do anywhere, even with Node.js</strong>'
         };
  
         transporter.sendMail(mailOptions, (error, info) => {
         if (error) {
         console.error('Error sending email:', error);
         process.exit(1);
         } else {
         console.log('Email sent:', info.messageId);
         process.exit(0);
         }
         });
         env:
         SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}




